name: Code Check

on:
  pull_request:

jobs:
  core_biome_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install
      
      - name: chmod +x biome
        run: |
          find node_modules/.pnpm -type f -path "*/@biomejs/biome/bin/biome" -exec chmod +x {} \;
          find node_modules/.pnpm -type f -path "*/@biomejs/cli-darwin-arm64/biome" -exec chmod +x {} \;
          find node_modules/.pnpm -type f -path "*/@biomejs/cli-linux-x64/biome" -exec chmod +x {} \;

      - name: Run Setup
        run: pnpm @core lint

  core_tsc_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install

      - name: Run Setup
        run: pnpm @core tsc

  ui_biome_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install

      - name: chmod +x biome
        run: |
          find node_modules/.pnpm -type f -path "*/@biomejs/biome/bin/biome" -exec chmod +x {} \;
          find node_modules/.pnpm -type f -path "*/@biomejs/cli-darwin-arm64/biome" -exec chmod +x {} \;
          find node_modules/.pnpm -type f -path "*/@biomejs/cli-linux-x64/biome" -exec chmod +x {} \;

      - name: Run Setup
        run: pnpm @ui lint:script
  
  ui_storybook_build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install

      - name: Build code
        run: pnpm @core build

      - name: Build code
        run: pnpm @ui build

      - name: Run Setup
        run: pnpm @ui build-storybook

  ui_stylelint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install

      - name: Run Setup
        run: pnpm @ui lint:style
        
  notify:
    runs-on: ubuntu-latest
    needs: [core_biome_check, core_tsc_check, ui_biome_check, ui_stylelint_check, ui_storybook_build_check]
    if: always()
    steps:
      - name: Send Slack notification on failure
        if: ${{ needs.core_biome_check.result == 'failure' || needs.core_tsc_check.result == 'failure' || needs.ui_biome_check.result == 'failure' || needs.ui_stylelint_check.result == 'failure' || needs.ui_storybook_build_check.result == 'failure' }}
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WORKFLOW_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "GitHub Actions failed! 🚨\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
